### ISSUE TITLE
add elyra to jupyter notebook

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/images-datascience#110]
[Elyra](https://elyra.readthedocs.io/en/latest/getting_started/overview.html) should be implement in our base jupyter images.

This could be done with multiple step : 
1. only local execution
2. argo worflow integration
3. other workflow engine if we add them in our stack

**Comment by avouacr** [comment]
Closing as the issue has become stale and Elyra is not common enough to justify being added to base images
