### ISSUE TITLE
Problem launching vscode service 503 error

### ISSUE THREAD

**Issue by raphaeleadjerad** [InseeFrLab/images-datascience#40]
- Erreur de lancement du service vscode aboutit à une erreur 503 Service Unavailable
- Tentative de remplacer par le service vscode-python, mais ne dispose pas des mêmes kernel (basesspcloud pas disponible) et des mêmes extensions (notebooks)

**Comment by avouacr** [comment]
- Le VSCode fonctionne correctement à présent
- Le nouvel environnement de référence est `base`, qui remplace et complète l'ancien `basesspcloud`
- Les notebooks fonctionnent également (même s'il y a un bug aléatoire de chargement qui semble affecter principalement Firefox)
