### ISSUE TITLE
change permission on /home/onyxia/.kube/config to make disappear warning terminal

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/images-datascience#43]
vscode and probably others Terminal launch a warning kube config file is group readable.

![image](https://user-images.githubusercontent.com/63847345/195755910-862e0d1a-cc99-4f85-acc6-788893324f2d.png)

As user onyxia is un groupe onyxia alone we could make /home/onyxia/.kube and recursive only rw from user.

![image](https://user-images.githubusercontent.com/63847345/195755986-1bfa3363-0458-4b8a-bfe6-ac731b312ce9.png)

**Comment by avouacr** [comment]
Fixed in 612f99f17db442059f8ce0537751711218d960c4
