### ISSUE TITLE
SparkR does not appear as being installed in rstudio-sparkr images

### ISSUE THREAD

**Issue by pierre-lamarche** [InseeFrLab/images-datascience#58]
Different issues to be raised when using the sparkr images:
- `SparkR` (also `sparklyr`) are not installed (despite this [line](https://github.com/InseeFrLab/images-datascience/blob/29e89750338eaaf85f91cff4ab3e1215432eff1b/spark/Dockerfile#L36) - probably the condition that does not work as expected). It would be nice to have `sparklyr` installed, as it better fits the RStudio IDE features (especially the Connections tab)
- in addition, I would expect the `tidyverse` to be there, so as to use it in combination to `sparlyr` (but I miss the `libxml2-dev` library).

If agreed, I can submit a PR.

**Comment by avouacr** [comment]
Solved in ac51f31f1b089a949392f97b8d3a0b91a7934bce
