### ISSUE TITLE
Ajoute extension observable à vscode

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/images-datascience#61]
Cette extension semble aider à la création de notebooks observable :

https://marketplace.visualstudio.com/items?itemName=GordonSmith.observable-js

@avouacr et @alexisdondon Etes-vous ok pour l'ajouter à l'image ?

**Comment by avouacr** [comment]
Ok pour moi pour tester

**Comment by avouacr** [comment]
done in #131
