### ISSUE TITLE
plusieurs paquets intéressants sont manquants dans l'image rstudio-sparkr 

### ISSUE THREAD

**Issue by jdlom** [InseeFrLab/images-datascience#76]
Il serait intéressant que rstudio-sparkr hérite  de `r-datascience`.
En effet, il manque par exemple `aws.s3`.

**Comment by avouacr** [comment]
On préfère éviter de tout mettre dans les mêmes images pour garder des tailles d'images raisonnables, du coup on a pris le parti d'hériter de `r-minimal` et de rajouter les packages essentiels pour le traitement des données issues de Spark. Je vais ajouter `aws.s3`, tu en vois d'autres ?

**Comment by jdlom** [comment]
ok, je comprends. à minima `paws `et `vaultr` (même si je n'ai jamais réussi à le faire fonctionner sur le sspcloud) que tu pourrais intégrer directement à `r-minimal` du coup

**Comment by avouacr** [comment]
Merci, c'est rajouté : #80 .
