### ISSUE TITLE
Add some labels in dockerfile

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/images-datascience#94]
add standard labels in docker like https://medium.com/@chamilad/lets-make-your-docker-image-better-than-90-of-existing-ones-8b1e5de950d

maintainers
one to have date build would be really useful in order to identify an image launch in onyxia is really tha latest or not

**Comment by avouacr** [comment]
Added maintainer label in #127. The date of build is already present by default in the metadata of docker images (key org.opencontainers.image.created, cf. [OCI spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md))
